export const enum Role {
  CEO = 'CEO',
  CFO = 'CFO',
  OPERATIONS_HEAD = 'OPERATIONS_HEAD',
  HR_HEAD = 'HR_HEAD',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  MANAGER = 'MANAGER',
  TEAM_LEAD = 'TEAM_LEAD',
  EMPLOYEE = 'EMPLOYEE',
}
